### ISSUE TITLE
Vulnerability: Every device is whitelisted during (re)boot

### ISSUE THREAD

**Issue by evilsocket** [hephaest0s/usbkill#36]
I was reading the code and [these lines](https://github.com/hephaest0s/usbkill/blob/master/usbkill.py#L127) came to my attention:

    start_devices = lsusb()
    acceptable_devices = set(start_devices + whitelisted_devices)
    
Considering the [discussion](https://twitter.com/evilsocket/status/596269535067508736) with @pwnsdx on twitter, this makes the pc vulnerable to the following scenario:

- Attacker has some kernel exploit to bypass login or read encryption keys from memory + physical access to the machine.
- It connects its usb pen with the exploit on it, the computer shuts down due to usbkill.
- He leaves his device attached and reboot the pc, now his device is put inside the acceptable_devices variable, thus whitelisted.

**Comment by pwnsdx** [comment]
Hey @evilsocket, thanks for reporting this possible issue!

I think I know why this line is here: It just prevent the computer from crashing instantly when the script boot by adding current connected devices to the whitelist. Once the whitelisted USB device removed, the computer crash.

However, I don't know if making a rogue USB drive with the same Vendor/Product ID can trick usbkill

**Comment by evilsocket** [comment]
let's put it this way ( hey this could be an idea for a second vuln! :D ) ... most computers have builtin usb devices ... if you execute lsusb with *nothing* attached you will still see your wifi interface, sometimes audio interfaces and so forth ... knowing the model of a pre assembled computer, an attacker could infer the exact vendor/product id of builtin usb peripherals and spoof them with, as you mentioned, a rogue usb device.

**Comment by pwnsdx** [comment]
Normally you are warned of this when you manually whitelist a device (so you have to hope that the attacker don't have these informations)

but for an USB device that is added when the script start… Let's wait for the answer of @hephaest0s

**Comment by evilsocket** [comment]
:+1:

**Comment by pwnsdx** [comment]
By the way, your scenario apply only to disks who are **not** fully encrypted (with Luks, Filevault etc)

If the disk is fully encrypted and the machine reboot then encryption keys are destroyed so the password to access to the datas will be needed :)

**Comment by evilsocket** [comment]
This is not my scenario, it's [your scenario](https://twitter.com/pwnsdx/status/596296288662065152) dude :) 
And what about [this](https://twitter.com/pwnsdx/status/596297551567003649) ? Make up your mind :D

Anyways, blindly whitelisting everything you find on boot IMHO is wrong ... you can take it into account and fix it or ignore it, your choice.

**Comment by pwnsdx** [comment]
I think we misunderstood.

https://mobile.twitter.com/pwnsdx/status/596296288662065152

You were saying here that "if you call yourself a security expert and leave your pc unlocked, you just deserve to be hacked"

My tweet was about this so you can understand even with a locked PC, as long as it is not shutdown the computer is still subject to attacks (like a kernel one for example).

usbkill can prevent this because once the attacker will plug his usb drive inside, the computer will shutdown.

**Comment by pwnsdx** [comment]
I think we misunderstood.

https://mobile.twitter.com/pwnsdx/status/596296288662065152

You were saying here that "if you call yourself a security expert and leave your pc unlocked, you just deserve to be hacked"

My tweet was about this so you can understand even with a locked PC, as long as it is not shutdown the computer is still subject to attacks (like a kernel one for example).

usbkill can prevent this because once the attacker will plug his usb drive inside, the computer will shutdown.

I'll be happy to know if there is a better solution than a blind whitelist of current connected devices when the user start the script because as far as I know, it's the duty of the user to manage his usb devices.

The only problem I see is the Vendor/Product ID spoof of a currently connected device.

- Is two devices with the same Vendor/Product will crash the computer?
- Is 0.5 seconds is enough time to flip the legit USB drive with a rogue one?

S.

**Comment by evilsocket** [comment]
maybe implement a "learning" mode where every device found is punt inside the whitelist and that's it ? then an option to manually add a device with the root password ... something like that I suppose should do the trick.

**Comment by pwnsdx** [comment]
> maybe implement a "learning" mode where every device found is punt inside the whitelist and that's it ? 

Your idea is worst than the current one because it involve saving informations on the hard drive.

Example: My friend give me an USB key and just after I run the script with that USB key connected: it will be saved forever in the config file. So let's suppose you don't know usbkill is saving this information and your friend a super-secret NSA agent. He will know the exact Product/Vendor ID to spoof.

> then an option to manually add a device with the root password ... something like that I suppose should do the trick.

The config file (where whitelist Vendor/Product IDs are) is owned by root so it is already the case.

**Comment by evilsocket** [comment]
well, then just remove the *start_devices* thingy :D

**Comment by pwnsdx** [comment]
I'm agree that this line is strange but it seem essential:
(Killing function has been replaced by print("HALT"))

![screen shot 2015-05-07 at 16 20 03](https://cloud.githubusercontent.com/assets/2057765/7517369/ede4f046-f4d4-11e4-87dd-4fb1e43ddc08.png)

**Comment by evilsocket** [comment]
dude whatever ... if you read some code, there shouldn't be **anything** that "seems strange", even if you have to refactor it all in order to have a correct implementation ... but again, it's not my choice, it's not my software ... it's yours :)   

Considering the media coverage usbkill had and the number of potential users now installing it, if you keep getting this approach maybe I'll do some PoC bypass of it with a **real** kernel exploit in a **real** scenario and post it to my blog.
I have **absolutely nothing** against you guys I really do appreciate your efforts, this has to be clear, but people should be aware that a solution they could be using is flawed by design ... we're talking about privacy&security ... this is not a game.

**Comment by pwnsdx** [comment]
I know security is not a game, thanks but I'm not the one who made the code so yes I can say "something is strange". That's why I said "Let's wait for the answer of @hephaest0s".

and, you are welcome to prove that usbkill can be bypassed.

**Comment by evilsocket** [comment]
yeah I was not talking to you directly buy as a general note :) I agree, let's wait for @hephaest0s :+1:

**Comment by pwnsdx** [comment]
:smiley:

**Comment by hephaest0s** [comment]
The first vul. described by evilsocket is a feature (as in, actually useful), not a bug.
usbkill assumes you have full disk encryption (or live disk living in ram, or some similar security measure). (before) boot-time attacks are not something that usbkill should prevent, because you have FDE. You should simply not unlock your computer if a pig's USB is in there...

If you fear an attack within seconds of unlocking your FDE, and before you started usbkill, then you should work with encrypted folders/containers. In this case you start your computer, start usbkill, and then unlock the rest.

The second vul./attack vector described by evilsocket is very real. When creating the white list feature I knew of this vulnerability, but was only concerned with trusted external USB devices that might be copied. I did put a warning in the config.
In order to defend against this attack (both for external and internal device ids) we want to look for the following. If two devices are connected with the same usbid, and this was not the case during program start, then there is an attack. I have no idea how lsusb (and the OSX version) deals with two devices sharing an id. Does it list both or just one?
I will look into the lsusb specification to find out, and change the program to better deal with custom-usbid attacks [which is now the name for that attack]. However, I do have a job and a boyfriend and will have to spend some time on both. I expect to have this issue fixed within two weeks and also the other pull request which fixes the settings and adds some other features.

Regards,
  Hephaestos

**Comment by evilsocket** [comment]
looking forward to see the fix, I'll dig into lsusb implementation asap

**Comment by pwnsdx** [comment]
After making some tests, I can confirm that there is a vulnerability (at least on OS X with system_profiler SPUSBDataType, the lsusb port on OS X is just a bridge to this command anyway).

I tried to replace the https://github.com/hephaest0s/usbkill/blob/master/usbkill.py#L141 with `if current_devices.count(device) != 1:` and added some prints so here is the debug:

> Started patrolling the USB ports every 0.5 seconds...
05ac:850b -- 1
0424:2514 -- 2
KILL COMPUTER
0bc2:a014 -- 1
0a5c:4500 -- 1
05ac:8215 -- 1
0424:2514 -- 2
KILL COMPUTER

"0424:2514" is actually a "Hub" and there are two as you can see:

>      Hub:
>
>        Product ID: 0x2514
>        Vendor ID: 0x0424  (SMSC)
>        Version: 0.03
>        Speed: Up to 480 Mb/sec
>        Location ID: 0xfa100000 / 2
>        Current Available (mA): 500
>        Current Required (mA): 2
>        Built-In: Yes
>
>     Hub:
> 
>          Product ID: 0x2514
>          Vendor ID: 0x0424  (SMSC)
>          Version: 0.03
>          Speed: Up to 480 Mb/sec
>          Location ID: 0xfd100000 / 2
>          Current Available (mA): 500
>          Current Required (mA): 2
>          Built-In: Yes

So it prove that it is possible to add a spoofed Product/Vendor ID USB drive due to the lack of checks at the line 141 (https://github.com/hephaest0s/usbkill/blob/master/usbkill.py#L141).

For the solution, we could use `if current_devices.count(device) != 1:` instead of `if device not in acceptable_devices:` and add a check to exclude "Build-In: Yes" (and be sure that this "Build-In: Yes" is not based on the Product/Vendor ID)

For GNU/Linux/BSD: I don't know as it use lsusb but here's a good start:

>  ```OPTIONS
>       -v, --verbose
>              Tells lsusb to be verbose and display detailed information about
>              the  devices shown.  This includes configuration descriptors for
>              the device's current speed.  Class descriptors  will  be  shown,
>              when  available,  for  USB  device classes including hub, audio,
>              HID, communications, and chipcard.
> ```

**Comment by pwnsdx** [comment]
Fix for OS X available: https://github.com/hephaest0s/usbkill/pull/43

**Comment by hephaest0s** [comment]
custom-usbid attack is now addressed on line 187 in commit [0]. This fix works for OSX as tested by pwnsdx. Likely for linux to, but not completely sure. Will look into it.

[0] https://github.com/hephaest0s/usbkill/commit/be2c7fda794a96dd9833f265e9741196ad8a0389
